# Generated by Django 3.2.8 on 2021-10-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.ManyToManyField(related_name='p', to='reviews.Publisher'),
        ),
    ]
