# Generated by Django 3.2.8 on 2021-10-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='test',
        ),
    ]
